import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import {
  LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer
} from 'recharts';
import { useAuth } from '../context/AuthContext';
import './ReportPage.css'; // Add separate CSS for printing and styling

const ReportPage = () => {
  const { t } = useTranslation();
  const { token } = useAuth();
  const [reportData, setReportData] = useState([]);
  const [crossValMessage, setCrossValMessage] = useState(null);
  const [crossValFailed, setCrossValFailed] = useState(false);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchReport = async () => {
      try {
        const response = await fetch('http://localhost:8000/report/data', {
          headers: { Authorization: `Bearer ${token}` }
        });
        if (!response.ok) throw new Error("Failed to load report");
        const data = await response.json();
        
        // Format data for Recharts
        const formattedData = data.data.map(item => ({
          week: `Week ${item.week_number}`,
          dateStr: new Date(item.week_start).toLocaleDateString(),
          mbi_score: item.mbi_score !== null ? parseFloat(item.mbi_score.toFixed(2)) : null,
          speech_score: item.speech_score !== null ? parseFloat(item.speech_score.toFixed(2)) : null,
          absolutist_index: item.absolutist_index !== null ? parseFloat(item.absolutist_index.toFixed(3)) : null,
          negative_word_ratio: item.negative_word_ratio !== null ? parseFloat(item.negative_word_ratio.toFixed(3)) : null,
          sentiment_polarity: item.sentiment_polarity !== null ? parseFloat(item.sentiment_polarity.toFixed(3)) : null,
        }));
        
        setReportData(formattedData);
        setCrossValFailed(data.cross_validation_failed);
        setCrossValMessage(data.cross_validation_message);
      } catch (error) {
        console.error("Failed to load report", error);
      } finally {
        setLoading(false);
      }
    };
    
    fetchReport();
  }, []);

  const handleDownloadPdf = () => {
    window.print();
  };

  if (loading) {
    return <div className="p-4 text-center">{t('Loading...', 'Загрузка...')}</div>;
  }

  return (
    <div className="report-container">
      <div className="report-header">
        <h1>{t('8-Week Progress Report', 'Отчет о динамике за 8 недель')}</h1>
        <button className="download-btn no-print" onClick={handleDownloadPdf}>
          {t('Download PDF', 'Скачать PDF')}
        </button>
      </div>

      {crossValFailed && (
        <div className="cross-val-warning">
          <strong>{t('Warning', 'Внимание')}:</strong> {crossValMessage}
        </div>
      )}

      <div className="chart-section">
        <h2>{t('Burnout Risk Index (Acoustics vs MBI)', 'Индекс риска выгорания (Акустика vs MBI)')}</h2>
        <div className="chart-wrapper">
          <ResponsiveContainer width="100%" height={300}>
            <LineChart data={reportData} margin={{ top: 5, right: 30, left: 20, bottom: 5 }}>
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis dataKey="week" />
              <YAxis domain={[0, 1]} />
              <Tooltip />
              <Legend />
              <Line type="monotone" dataKey="speech_score" name={t('Acoustic Score', 'Акустический показатель')} stroke="#8884d8" activeDot={{ r: 8 }} connectNulls />
              <Line type="monotone" dataKey="mbi_score" name={t('MBI Score', 'Показатель MBI')} stroke="#82ca9d" connectNulls />
            </LineChart>
          </ResponsiveContainer>
        </div>
      </div>

      <div className="chart-section">
        <h2>{t('Linguistic & Semantic Features', 'Лингвистические и семантические признаки')}</h2>
        <div className="chart-wrapper">
          <ResponsiveContainer width="100%" height={300}>
            <LineChart data={reportData} margin={{ top: 5, right: 30, left: 20, bottom: 5 }}>
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis dataKey="week" />
              <YAxis domain={[-1, 1]} />
              <Tooltip />
              <Legend />
              <Line type="monotone" dataKey="absolutist_index" name={t('Absolutist Index', 'Индекс абсолютизма')} stroke="#ff7300" connectNulls />
              <Line type="monotone" dataKey="negative_word_ratio" name={t('Negative Word Ratio', 'Доля негативных слов')} stroke="#ff0000" connectNulls />
              <Line type="monotone" dataKey="sentiment_polarity" name={t('Sentiment Polarity', 'Полярность тональности')} stroke="#387908" connectNulls />
            </LineChart>
          </ResponsiveContainer>
        </div>
      </div>
      
      <div className="report-footer print-only">
        <p>{t('Generated by Burnout Predictor System', 'Сгенерировано системой Burnout Predictor')}</p>
        <p>{new Date().toLocaleDateString()}</p>
      </div>
    </div>
  );
};

export default ReportPage;
